server:
    port: 8001

spring:
    application:
        name: hr-worker
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:database
        username: sa
        password: res
        driverClassName: org.h2.Driver
    jpa:
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
            platform: h2
